name: Publish Docker Image
on:
  push:
    tags:        
      - '*'
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker_file: Dockerfile
            platforms: linux/arm64,linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Container Registry
      run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Build and Publish the Docker image
      run: |
        DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker buildx build . --no-cache --platform=${{ matrix.platforms }} -t "${DOCKER_IMAGE}" -f ${{ matrix.docker_file }} --push
